layerrules = true
kill_bind = "ctrl+shift+alt, h"
version = 1

[windows]
scale = 8.5
items_per_row = 5

[windows.overview]
strip_html_from_workspace_title = true
key = "f13"
modifier = "shift"
filter_by = []
hide_filtered = false

[windows.overview.launcher]
default_terminal = "WAYLAND_DISPLAY=1 wezterm"
launch_modifier = "ctrl"
width = 650
max_items = 5
show_when_empty = true
animate_launch_ms = 250

[windows.overview.launcher.plugins.applications]
run_cache_weeks = 4
show_execs = true
show_actions_submenu = false

[windows.overview.launcher.plugins.terminal]

[windows.overview.launcher.plugins.shell]

[[windows.overview.launcher.plugins.websearch.engines]]
url = "https://duckduckgo.com/?q={}"
name = "DuckDuckGo"
key = "d"

[windows.overview.launcher.plugins.calc]

[windows.switch]
modifier = "super"
filter_by = []
show_workspaces = false
